# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV DJANGO_SETTINGS_MODULE=yappify.settings

# Run app.py when the container launches
CMD ["gunicorn", "yappify.wsgi:application", "--bind", "0.0.0.0:8000"]
