version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yappify_user
      POSTGRES_PASSWORD: yappifypass
      POSTGRES_DB: YappifyDatabase
